name = "SatplanExamples"
uuid = "bf626f29-1358-418b-8291-66be18e504e1"
authors = ["Jan Vanhove <janvanhove@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
